export const ANSWERS_GET_SUCCESS = 'ANSWERS_GET_SUCCESS';
export const ANSWERS_GET_FAILURE = 'ANSWERS_GET_FAILURE';

export const ANSWERS_GET_SINGLE_SUCCESS = 'ANSWERS_GET_SINGLE_SUCCESS';
export const ANSWERS_GET_SINGLE_FAILURE = 'ANSWERS_GET_SINGLE_FAILURE';

export const ANSWERS_CREATE_SUCCESS = 'ANSWERS_CREATE_SUCCESS';
export const ANSWERS_CREATE_FAILURE = 'ANSWERS_CREATE_FAILURE';

export const ANSWERS_FEEDBACK_SUCCESS = 'ANSWERS_FEEDBACK_SUCCESS';
export const ANSWERS_FEEDBACK_FAILURE = 'ANSWERS_FEEDBACK_FAILURE';

export const ANSWERS_DELETE_SUCCESS = 'ANSWERS_DELETE_SUCCESS';
export const ANSWERS_DELETE_FAILURE = 'ANSWERS_DELETE_FAILURE';
