export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS';
export const USERS_GET_FAILURE = 'USERS_GET_FAILURE';

export const USERS_GET_SINGLE_SUCCESS = 'USERS_GET_SINGLE_SUCCESS';
export const USERS_GET_SINGLE_FAILURE = 'USERS_GET_SINGLE_FAILURE';

export const USERS_CREATE_SUCCESS = 'USERS_CREATE_SUCCESS';
export const USERS_CREATE_FAILURE = 'USERS_CREATE_FAILURE';

export const USERS_UPDATE_SUCCESS = 'USERS_UPDATE_SUCCESS';
export const USERS_UPDATE_FAILURE = 'USERS_UPDATE_FAILURE';

export const USERS_MOST_ANSWERS_SUCCESS = 'USERS_MOST_ANSWERS_SUCCESS';
export const USERS_MOST_ANSWERS_FAILURE = 'USERS_MOST_ANSWERS_FAILURE';

export const USERS_DELETE_SUCCESS = 'USERS_DELETE_SUCCESS';
export const USERS_DELETE_FAILURE = 'USERS_DELETE_FAILURE';
