export const QUESTIONS_GET_SUCCESS = 'QUESTIONS_GET_SUCCESS';
export const QUESTIONS_GET_FAILURE = 'QUESTIONS_GET_FAILURE';

export const QUESTIONS_GET_HOT_SUCCESS = 'QUESTIONS_GET_HOT_SUCCESS';
export const QUESTIONS_GET_HOT_FAILURE = 'QUESTIONS_GET_HOT_FAILURE';

export const QUESTIONS_GET_SINGLE_SUCCESS = 'QUESTIONS_GET_SINGLE_SUCCESS';
export const QUESTIONS_GET_SINGLE_FAILURE = 'QUESTIONS_GET_SINGLE_FAILURE';

export const QUESTIONS_CREATE_SUCCESS = 'QUESTIONS_CREATE_SUCCESS';
export const QUESTIONS_CREATE_FAILURE = 'QUESTIONS_CREATE_FAILURE';

export const QUESTIONS_FEEDBACK_SUCCESS = 'QUESTIONS_FEEDBACK_SUCCESS';
export const QUESTIONS_FEEDBACK_FAILURE = 'QUESTIONS_FEEDBACK_FAILURE';
